spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/projReservaEsporte_api
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.show-sql=true

aws.access-key-id=
aws.secret-access-key=
aws.region=us-east-1
aws.s3.bucket-name=proj-quadras-s3
